CREATE TABLE "SYSTEM" (
    ID INTEGER NOT NULL PRIMARY KEY
  , TYPE TEXT
  , STUDENT_ID TEXT NOT NULL
  , PATH TEXT NOT NULL
  , POSITION TEXT
  , is_mask INTEGER
  , TIME TEXT NOT NULL
  , HOMEWORK TEXT
  , is_commit INTEGER
  , LESSON TEXT
  , annotation TEXT
  , UNIQUE(ID ASC)
);
